language: node_js

node_js:
  - node

services:
  - docker

install: 
  - cd build && npm install && npm start && cd ..

before_script:
  - rm -rf system/.htaccess system/*/.htaccess

jobs:
  include:
    - stage: build docker image
      script: bash ./dockerpublish.sh